#### $$IMPLEMENTING ~~ CLASSIFICATION ~~TECHNIQUE$$ 

In [40]:
import numpy as np 
import pandas as pd 
import re
import nltk 

In [41]:
#Reading the User Review CSV
test=pd.read_csv('review_sentiment1.csv')
test

In [42]:
test

Unnamed: 0  Unnamed: 0.1  \
0               0             0   
1               1             1   
2               2             2   
3               3             3   
4               4             4   
...           ...           ...   
83986       83986         83986   
83987       83987         83987   
83988       83988         83988   
83989       83989         83989   
83990       83990         83990   

                                               Game_Name     Platform  \
0                   The Legend of Zelda: Ocarina of Time  Nintendo 64   
1                   The Legend of Zelda: Ocarina of Time  Nintendo 64   
2                   The Legend of Zelda: Ocarina of Time  Nintendo 64   
3                   The Legend of Zelda: Ocarina of Time  Nintendo 64   
4                   The Legend of Zelda: Ocarina of Time  Nintendo 64   
...                                                  ...          ...   
83986  Monkey Island 2 Special Edition: LeChuck's Rev...           PC   
83987  Monkey Island 2 Special Edition: LeChuck's Rev...           PC   
83988  Monkey Island 2 Special Edition: LeChuck's Rev...           PC   
83989  Monkey Island 2 Special Edition: LeChuck's Rev...           PC   
83990  Monkey Island 2 Special Edition: LeChuck's Rev...           PC   

      Review_Date                                        User_Review  \
0       25-Apr-11  I won't bore you with what everyone is already...   
1        9-Jun-11  I'm one of those people who think that this is...   
2       25-Nov-10  Anyone who gives the masterpiece below a 7 or ...   
3       12-Jun-11  Everything in OoT is so near at perfection, it...   
4       21-Mar-10  This game is the highest rated game on Metacri...   
...           ...                                                ...   
83986    2-Jun-19  I am one of the players who never played the o...   
83987   18-Mar-17  If I had played this game 25 years ago, I'm su...   
83988   18-Oct-19  This game is pretty fun. Good times were had b...   
83989    6-Sep-20  Вторая часть оказалось чуть лучше первой, а им...   
83990    1-May-20  And here is the best point and click graphic a...   

       User_Rating                                       clean_review  \
0               10  bore everyone already saying amazing game fenc...   
1               10  one people think greatest game time matter qua...   
2               10  anyone give masterpiece 7 8 either hate astoun...   
3               10  everything oot near perfection really wonder g...   
4               10  game highest rated game metacritic good reason...   
...            ...                                                ...   
83986            9  one player never played original started adven...   
83987            7  played game 25 year ago sure would enjoyed rem...   
83988            8  game pretty fun good time best monkey time fun...   
83989            4  вторая часть оказалось чуть лучше первой а име...   
83990            9  best point click graphic adventure ever played...   

                                               Sentiment  Polarity  \
0      Sentiment(polarity=0.12222222222222223, subjec...      0.12   
1      Sentiment(polarity=0.024100776674306094, subje...      0.02   
2      Sentiment(polarity=0.1302631578947368, subject...      0.13   
3      Sentiment(polarity=0.09200000000000001, subjec...      0.09   
4      Sentiment(polarity=-0.0090909090909091, subjec...     -0.01   
...                                                  ...       ...   
83986  Sentiment(polarity=0.18045977011494252, subjec...      0.18   
83987  Sentiment(polarity=0.13653846153846155, subjec...      0.14   
83988  Sentiment(polarity=0.29999999999999993, subjec...      0.30   
83989          Sentiment(polarity=0.0, subjectivity=0.0)      0.00   
83990  Sentiment(polarity=0.5033333333333333, subject...      0.50   

       Subjectivity  Reviews_Sentiment  
0              0.49                  1  
1              0.46                  1  
2  

In [43]:
#Feature extraction from reviews
features = test.iloc[:, 7].values
labels = test.iloc[:, 11].values

In [44]:
features

array(['bore everyone already saying amazing game fence whether give classic try go read ign review ',
       'one people think greatest game time matter quality game ever plain best game ever played partly first good game actually played first got nintendo 64 considerably young yet every game played thought absolutely horrible hadi one people think greatest game time matter quality game ever plain best game ever played partly first good game actually played first got nintendo 64 considerably young yet every game played thought absolutely horrible simple objective game child thought hard pointless one day ocarina time brought home first refused play watched father play straight away something entirely new different also time real least brought ability actually explore get know people even people talked repeated thing matter many time talked matter game something new exciting day get good old nostalgic feeling whenever play one greatest story time video game one first create sort univer

In [45]:
#Specifying labels for the extracted features
labels

array([1, 1, 1, ..., 1, 0, 1])

In [46]:
processed_features = []

for sentence in range(0, len(features)):
    # Remove all the special characters
    processed_feature = re.sub(r'\W', ' ', str(features[sentence]))

    # remove all single characters
    processed_feature= re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_feature)

    # Remove single characters from the start
    processed_feature = re.sub(r'\^[a-zA-Z]\s+', ' ', processed_feature) 

    # Substituting multiple spaces with single space
    processed_feature = re.sub(r'\s+', ' ', processed_feature, flags=re.I)

    # Removing prefixed 'b'
    processed_feature = re.sub(r'^b\s+', '', processed_feature)

    # Converting to Lowercase
    processed_feature = processed_feature.lower()

    processed_features.append(processed_feature)

In [47]:
#Clean Reviews  
processed_features

['bore everyone already saying amazing game fence whether give classic try go read ign review ',
 'one people think greatest game time matter quality game ever plain best game ever played partly first good game actually played first got nintendo 64 considerably young yet every game played thought absolutely horrible hadi one people think greatest game time matter quality game ever plain best game ever played partly first good game actually played first got nintendo 64 considerably young yet every game played thought absolutely horrible simple objective game child thought hard pointless one day ocarina time brought home first refused play watched father play straight away something entirely new different also time real least brought ability actually explore get know people even people talked repeated thing matter many time talked matter game something new exciting day get good old nostalgic feeling whenever play one greatest story time video game one first create sort universe one first

In [48]:
from nltk.corpus import stopwords
#Importing the TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
#Creating Tfid Vectorizer
vectorizer = TfidfVectorizer (max_features=2500, min_df=7, max_df=0.8, stop_words=stopwords.words('english'))
processed_features = vectorizer.fit_transform(processed_features).toarray()

In [49]:
from sklearn.model_selection import train_test_split
#Spliting the data into train & test
X_train, X_test, y_train, y_test = train_test_split(processed_features, labels, test_size=0.2, random_state=0)


In [50]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [51]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [52]:
y_train

array([1, 0, 1, ..., 1, 0, 1])

In [53]:
y_test

array([1, 1, 0, ..., 1, 0, 0])

### 1) Random Forest Classifier

In [54]:
#Importing the RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
#Initializing the RandomForestClassifier
text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)
text_classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=0)

In [55]:
predictions = text_classifier.predict(X_test)

In [56]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
#Determining the Prediction Accuracy
print(accuracy_score(y_test, predictions))

[[ 3308  2171]
 [  485 10835]]
              precision    recall  f1-score   support

           0       0.87      0.60      0.71      5479
           1       0.83      0.96      0.89     11320

    accuracy                           0.84     16799
   macro avg       0.85      0.78      0.80     16799
weighted avg       0.85      0.84      0.83     16799

0.8418953509137449


### 2) Decision Tree Classifier


In [57]:
#Importing the DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
#Initializing the DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
predictions = dtree.predict(X_test)

In [58]:
print(confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))
#Determining the Prediction Accuracy
dtree.score(X_test, y_test)

[[3553 1926]
 [1969 9351]]


              precision    recall  f1-score   support

           0       0.64      0.65      0.65      5479
           1       0.83      0.83      0.83     11320

    accuracy                           0.77     16799
   macro avg       0.74      0.74      0.74     16799
weighted avg       0.77      0.77      0.77     16799



0.7681409607714745

### 3) KNN Algorithm

In [59]:
#Importing the KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
#Initializing the KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=200)
knn.fit(X_train, y_train)
pred = knn.predict(X_test)

In [60]:
print(confusion_matrix(y_test, pred))
print('\n')
print(classification_report(y_test, pred))
#Determining the Prediction Accuracy
knn.score(X_test, y_test)

[[ 5463    16]
 [11174   146]]


              precision    recall  f1-score   support

           0       0.33      1.00      0.49      5479
           1       0.90      0.01      0.03     11320

    accuracy                           0.33     16799
   macro avg       0.61      0.50      0.26     16799
weighted avg       0.71      0.33      0.18     16799



0.33388892195964043

Random Forest has the Highest Accuracy with 84.14% Accuracy.